### PR TITLE
onError now passes exception object, fixed stubs, test for unhandled exceptions

### PR DESCRIPTION
**Pull request by jamesaspence**
- Any call of `onError` inside the node SDK now passes the entire exception object rather than just the message.
- New unit test to ensure that unexpected exceptions are caught and handled via `onError` properly
- Stubs of `axios.post` via `sandbox.stub` now resolve properly and return a promise (removing the unexpected exceptions).

### CODE REVIEW

**Comment by jamesaspence** [comment]
I planned to change the `sumologic.logger.js` as well, but was unsure what `xmlHttp.addEventListener('error')` returned to its callback as a parameter (might be a event object?), so I didn't feel comfortable updating that one. Might revisit if I have time and update that as well though!

**Comment by clementallen** [comment]
LGTM 👍 - @billsaysthis the travis builds are failing due to snyk not being authenticated - are you able to fix this please?

**Comment by billsaysthis** [comment]
Will look into it today

**Comment by billsaysthis** [comment]
Pushed a new version that removed Snyk, please merge master into your branch.

**Comment by jamesaspence** [comment]
On it!

**Comment by jamesaspence** [comment]
@billsaysthis can we re-run the build?

**Comment by billsaysthis** [comment]
Apparently you can just close the PR and reopen it to trigger a rebuild.

**Comment by billsaysthis** [comment]
This has been published as v1.5.3 -- thanks!

**Pull request merged**
